; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "WebScreenSaver"
#define MyAppVersion "0.4"
#define MyAppExeName "WebScreenSaver.scr"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9FF5F5C1-3002-42DA-95B3-C252A5CFE428}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={commonpf32}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\MyCode\ScreenSaverClock
OutputBaseFilename=Web屏保_v{#MyAppVersion}_Installer
SolidCompression=yes
WizardStyle=modern windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\web\*"; DestDir: "{app}\web"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.WinForms.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\Microsoft.Web.WebView2.Wpf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\WebScreenSaver.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\WebScreenSaver.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\MyCode\ScreenSaverClock\WinFormsApp1\bin\Release\net8.0-windows\WebScreenSaver.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent
Filename: "{win}\explorer.exe"; Parameters: """{app}"""; Flags: postinstall skipifsilent; Description: "打开安装文件夹"

[Messages]
FinishedLabel=请进入安装文件夹，在scr文件上右键点击“安装”以启用屏幕保护程序！